// Calibrate the microworld's win-condition banner: prove it can say BEATEN, per clause.
//
// WHY THIS EXISTS. The page tells a judge "you have beaten it if this says BEATEN". A banner that
// can only ever say CONTRACT HOLDS is an uncalibrated instrument, and it would be worse than no
// banner because it invites a challenge it cannot honour. The sanitizer is correct, so no real
// input reaches BEATEN, which means the only way to show the verdict works is to plant an output
// that violates each clause and require the check to catch it.
//
// It extracts `forbidden` and `contract` FROM THE GENERATED PAGE rather than restating them, so
// this cannot drift from what ships. `run` is stubbed as identity, which makes the idempotence
// clause hold by construction and is why that clause has its own explicit case below.
//
//   node sanitizer-microworld/check_verdict.js

const fs = require("fs");
const path = require("path");

const PAGE = path.join(__dirname, "index.html");
const src = fs.readFileSync(PAGE, "utf8");

function extract(name) {
  const start = src.indexOf(`function ${name}(`);
  if (start < 0) throw new Error(`ANCHOR MISSING: function ${name} is not in the page`);
  let depth = 0, i = src.indexOf("{", start);
  for (let j = i; j < src.length; j++) {
    if (src[j] === "{") depth++;
    else if (src[j] === "}" && --depth === 0) return src.slice(start, j + 1);
  }
  throw new Error(`unbalanced braces reading ${name}`);
}

const CAP_M = src.match(/const CAP = (\d+);/);
if (!CAP_M) throw new Error("ANCHOR MISSING: const CAP");
const harness = `
${CAP_M[0]}
let RUN_RESULT = null;
function run(s) { return RUN_RESULT === null ? { text: s, stripped: 0 } : RUN_RESULT; }
${extract("forbidden")}
${extract("contract")}
`;
// Loaded as a temp MODULE rather than through `new Function`, which keeps the flagged
// string-interpolation pattern out of the tree. The text executed is our own build artifact
// (index.html is generated by build_page.py from a template in this repo), never external input.
const os = require("os");
const tmpdir = fs.mkdtempSync(path.join(os.tmpdir(), "zc-verdict-"));
const tmp = path.join(tmpdir, "harness.js");
fs.writeFileSync(
  tmp,
  harness + "\nmodule.exports = { contract, setRun: (v) => { RUN_RESULT = v; } };",
  "utf8",
);
const ctx = require(tmp);

let cases = 0;
const failures = [];
function check(name, got, want) {
  cases++;
  if (got !== want) failures.push(`${name}: got ${JSON.stringify(got)}, want ${JSON.stringify(want)}`);
}
const beaten = (out) => ctx.contract(out).some(([, ok]) => !ok);
const failing = (out) => ctx.contract(out).filter(([, ok]) => !ok).map(([l]) => l);

// The POSITIVE control first: ordinary sanitized output must HOLD, or every case below is
// satisfied by a check that simply always fails.
ctx.setRun(null);
check("ordinary output HOLDS", beaten("Acme Coffee"), false);
check("empty output HOLDS", beaten(""), false);

// One planted violation per clause of assert_output_contract.
check("over the cap is BEATEN", beaten("x".repeat(97)), true);
check("exactly at the cap HOLDS", beaten("x".repeat(96)), false);
check("a control character is BEATEN", beaten("AcmeCoffee"), true);
check("a zero-width character is BEATEN", beaten("Acme​Coffee"), true);
check("a bidi override is BEATEN", beaten("Acme‮Coffee"), true);
check("a line separator is BEATEN", beaten("Acme Coffee"), true);
check("a leading space is BEATEN", beaten(" Acme"), true);
check("a trailing space is BEATEN", beaten("Acme "), true);
check("a doubled space is BEATEN", beaten("Acme  Coffee"), true);

// Idempotence needs the stub to LIE, because with identity `run` it can never fail.
ctx.setRun({ text: "something else", stripped: 0 });
check("a non-idempotent second pass is BEATEN", beaten("Acme"), true);
ctx.setRun({ text: "Acme", stripped: 3 });
check("a second pass that still strips is BEATEN", beaten("Acme"), true);
ctx.setRun(null);

// Each clause must be reachable INDIVIDUALLY, so a single over-eager clause cannot stand in for
// all of them. Six clauses, and the count is asserted so adding one without a case goes red.
check("the contract has six clauses", ctx.contract("Acme").length, 6);
check("the cap clause names itself", failing("x".repeat(97))[0].includes("bounded"), true);
check("the forbidden clause names itself", failing("AB")[0].includes("control"), true);
check("the leading-space clause is alone", failing(" Acme").length, 1);
check("the trailing-space clause is alone", failing("Acme ").length, 1);
check("the doubled-space clause is alone", failing("Acme  Coffee").length, 1);

for (const f of failures) console.log(`  FAIL  ${f}`);
console.log(`verdict calibration: ${cases - failures.length}/${cases}`);
process.exit(failures.length ? 1 : 0);
